### ISSUE TITLE
Error in stage 7?

### ISSUE THREAD

**Issue by rohitpaulk** [codecrafters-io/build-your-own-dns-server#21]
> Hi there, I think there is an error in your test for stage 7 of the DNS Server challenge. The pointer is 0xc010 when I think the correct value should be 0xc004. Could you please verify this?

**Comment by rohitpaulk** [comment]
@RamitGoolry feel free to add any extra details here - if you could print out the full bytes you're receiving in hex format, vs. what you think they should be, that'd be ideal

**Comment by RamitGoolry** [comment]
@rohitpaulk, thanks for reaching out! I actually realized as I was explaining the error in this comment that I was mistaken. I was mistakenly reading the 16th byte from the start of the **question section** not the start of the whole DNS message.

Since the header section is 12 bytes, that explains the difference of 12 bytes from 0x10 to 0x04. We can close this issue. Thanks again.

**Comment by rohitpaulk** [comment]
Gotcha, no problem. Thank you for sharing the context!
